runtime: nodejs16
env_variables:
  AUTH0_JWK_URI: "https://assignment3.api"
  DATABASE_URL: 'mysql://username:password@aws.connect.psdb.cloud/deploy-test?sslaccept=strict'
  AUTH0_AUDIENCE: "https://assignment3.api"
  AUTH0_ISSUER: "https://yukumo29.us.auth0.com/"
  PORT: 8080
